#pragma once

#define KH1VITA_DATA_ROOT "ux0:data/KH1VITA"
#define KH1VITA_GAME_ROOT KH1VITA_DATA_ROOT "/game"
#define KH1VITA_KINGDOM_ROOT KH1VITA_DATA_ROOT "/kingdom"
#define KH1VITA_LOG_PATH KH1VITA_DATA_ROOT "/port.log"

#define KH1VITA_SCREEN_WIDTH 960
#define KH1VITA_SCREEN_HEIGHT 544
#define KH1VITA_SCREEN_PITCH 960
